name: build runtime
on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build-mac:
#    if: ${{ false }}  # disable
    name: mac
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, arm64]
    steps:
      - uses: actions/checkout@v3
      - name: compile runtime
        run: |
          make ARCH=${{ matrix.platform }} lo
      - name: compile core.so
        run: |
          make ARCH=${{ matrix.platform }} BINDING=core module
      - name: test
        if: ${{ matrix.platform == 'x64' }}      
        run: |
          make test
      - name: upload core.so artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/binding/core/core.so
          name: core-mac-${{ matrix.platform }}.so
      - name: upload runtime artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/lo
          name: lo-mac-${{ matrix.platform }}

  build-linux-x64:
#    if: ${{ false }}  # disable
    name: linux-x64
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
    steps:
      - uses: actions/checkout@v3
      - name: compile
        run: |
          make lo
      - name: test
        run: |
          make test
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/lo
          name: lo-linux-x64

  build-linux-arm:
#    if: ${{ false }}  # disable
    name: linux-arm64
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
    steps:
      - uses: actions/checkout@v3
      - name: install arm64 tools
        run: |
          sudo apt-get install -qy binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: compile
        run: |
          make ARCH=arm64 C=aarch64-linux-gnu-gcc CC=aarch64-linux-gnu-g++ lo
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/lo
          name: lo-linux-arm64
  
  build-windows:
#    if: ${{ false }}  # disable
    name: windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.platform }}
      - name: compile
        run: |
          make lo.exe
      - name: test
        run: |
          make test
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/lo.exe
          name: lo.exe
