name: build and upload artifacts for release
on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:

  build-mac:
#    if: ${{ false }}  # disable
    name: mac
    runs-on: macos-12
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, arm64]
    steps:
      - uses: actions/checkout@v3
      - name: compile
        run: |
          make ARCH=${{ matrix.platform }} cleanall lo
      - name: compress runtime
        run: |
          gzip -9 -c lo > lo-mac-${{ matrix.platform }}.tar.gz
      - name: upload compressed artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: lo-mac-${{ matrix.platform }}.gz
          asset_name: lo-mac-${{ matrix.platform }}.gz
          asset_content_type: application/gzip

  build-linux-x64:
#    if: ${{ false }}  # disable
    name: linux-x64
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
    steps:
      - uses: actions/checkout@v3
      - name: compile
        run: |
          make cleanall lo test
      - name: compress runtime
        run: |
          gzip -9 -c lo > lo-linux-x64.tar.gz
      - name: upload compressed artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: lo-linux-x64.gz
          asset_name: lo-linux-x64.gz
          asset_content_type: application/gzip

  build-linux-arm:
#    if: ${{ false }}  # disable
    name: linux-arm64
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
    steps:
      - uses: actions/checkout@v3
      - name: install arm64 tools
        run: |
          sudo apt-get install -qy binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: compile
        run: |
          make ARCH=arm64 C=aarch64-linux-gnu-gcc CC=aarch64-linux-gnu-g++ cleanall lo
      - name: compress runtime
        run: |
          gzip -9 -c lo > lo-linux-arm64.gz
      - name: upload compressed artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: lo-linux-arm64.gz
          asset_name: lo-linux-arm64.gz
          asset_content_type: application/gzip

  build-windows:
#    if: ${{ false }}  # disable
    name: windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [x64]
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.platform }}
      - name: compile
        run: |
          make lo.exe test
      - name: compress runtime
        run: |
          gzip -9 -c lo.exe > lo.exe.gz
      - name: upload compressed artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: lo.exe.gz
          asset_name: lo.exe.gz
          asset_content_type: application/gzip
